# website settings
website:
  title: "About"
  description: "William Fernandez- Doctoral Researcher"   # A brief slogan (optional)
  image: img/Picture1.jpg
    
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true

    # Sub-pages
    left:
      - text: "Research"
        href: research/index.qmd
      - text: "Teaching"
        href: teaching/index.qmd
      - text: "CV"
        href: cv/index.qmd
      - text: "Hobbies"
        href: hobbies/index.qmd
    
    # Social media handles
    right:
      - icon: envelope
        aria-label: email
        href: "mailto:w.fernandez@hertie-school.org"  
  

# General configuration
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2025 William Fernandez</span>
    
project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - lux
    css: styles.css
    toc: true
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true