# website settings
website:
  title: "William Fernandez"                                                # Your name
  description: "Doctoral Researcher at DYNAMICS RTG"   # A brief slogan (optional)
  image: img/my_image.jpeg
    
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true

    # Sub-pages
    left:
      - text: "Publications"
        href: publications/index.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "CV"
        href: cv/index.qmd
      - text: "Blog"
        href: blog/index.qmd
    
    # Social media handles
    right:
      - icon: twitter
        href: https://x.com/William_FT
      - icon: github
        href: https://github.com/williamfernandezt
      - icon: linkedin
        href: https://www.linkedin.com/in/william-fernandez-47a730114/
      - icon: envelope
        aria-label: email
        href: "mailto:w.fernandezt@outlook.com"  
  

# General configuration
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2024 William Fernandez</span>
    right: |
      <span class="faux-block"><a href="https://github.com/williamfernandezt/quarto-website-template/">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - lux
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true